# fly.toml app configuration file generated for dreamhouse-ai on 2025-03-12T09:05:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dreamhouse-ai'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[build.args]
  NEXT_PUBLIC_POSTHOG_KEY = "phc_2ZKWOWhslFYmnPpRuEVnUX8NFgGh7srzCA3QSEeG1yn"
  NEXT_PUBLIC_POSTHOG_HOST = "https://eu.i.posthog.com"

[env]
  PORT = '3000'
  NEXT_PUBLIC_POSTHOG_KEY = "phc_2ZKWOWhslFYmnPpRuEVnUX8NFgGh7srzCA3QSEeG1yn"
  NEXT_PUBLIC_POSTHOG_HOST = "https://eu.i.posthog.com"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
